name: Flutter Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_appbundle:
    name: Flutter Release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Move to project directory
        run: cd geo_gallery
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Get dependencies
        run: flutter pub get
      - name: Clean build
        run: flutter clean
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
