name: Flutter Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_appbundle:
    name: Flutter Release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        path: geo_gallery
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
        working-directory: geo_gallery
      - name: Get dependencies
        run: flutter pub get
        working-directory: geo_gallery
      - name: Clean build
        run: flutter clean
        working-directory: geo_gallery
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
        working-directory: geo_gallery
