name: Dart CI

on: push

env:
  flutter_channel: 'stable'
  flutter_version: '2.2.2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Get dependencies
      run: flutter pub get
      working-directory: geo_gallery

    - name: Build APK
      run: flutter build apk
      working-directory: geo_gallery
